# Generated by Django 2.0.6 on 2018-06-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注信息')),
                ('assetsgroup', models.ManyToManyField(to='assets.AssetGroup', verbose_name='资产组')),
                ('group', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '权限信息',
                'verbose_name_plural': '权限信息',
                'db_table': 'asset_permission',
                'permissions': (('can_add_asset_permission', '添加资产组权限'), ('can_change_asset_permission', '修改资产组权限'), ('can_delete_asset_permission', '删除资产组权限'), ('can_view_asset_permission', '查看资产组权限')),
            },
        ),
    ]
