# Generated by Django 2.0.6 on 2018-06-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NAVI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.URLField(verbose_name='网址')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '站点导航',
                'verbose_name_plural': '站点导航',
                'db_table': 'navi',
                'permissions': (('can_add_navi', '添加站点'), ('can_change_navi', '修改站点'), ('can_delete_navi', '删除站点'), ('can_view_navi', '查看站点')),
            },
        ),
    ]
