# Generated by Django 2.0.6 on 2018-06-13 02:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='资产组名称')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '资产组',
                'verbose_name_plural': '资产组',
                'db_table': 'assetgroup',
                'permissions': (('can_add_assetgroup', '添加资产组'), ('can_change_assetgroup', '修改资产组'), ('can_delete_assetgroup', '删除资产组'), ('can_view_assetgroup', '查看资产组')),
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='管理IP')),
                ('other_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='其它IP')),
                ('asset_type', models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器'), ('4', '网络设备'), ('5', '其他')], max_length=30, null=True, verbose_name='设备类型')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=30, null=True, verbose_name='设备状态')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作系统')),
                ('cpu_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU数量')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='硬盘信息')),
                ('sn', models.CharField(max_length=60, unique=True, verbose_name='SN号码')),
                ('usage', models.CharField(blank=True, max_length=100, null=True, verbose_name='用途')),
                ('application', models.CharField(blank=True, max_length=100, null=True, verbose_name='软件')),
                ('principal', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('jira', models.CharField(blank=True, max_length=200, null=True, verbose_name='申请jira')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.AssetGroup', verbose_name='资产组')),
            ],
            options={
                'verbose_name': '资产信息',
                'verbose_name_plural': '资产信息',
                'db_table': 'assets',
                'permissions': (('can_add_asset', '添加资产'), ('can_change_asset', '修改资产'), ('can_delete_asset', '删除资产'), ('can_view_asset', '查看资产')),
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='机房名称')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='机房地址')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='机房电话')),
                ('contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户经理')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'db_table': 'idc',
                'permissions': (('can_add_idc', '添加机房'), ('can_change_idc', '修改机房'), ('can_delete_idc', '删除机房'), ('can_view_idc', '查看机房')),
            },
        ),
        migrations.AddField(
            model_name='assets',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Idc', verbose_name='所在机房'),
        ),
    ]
